/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.cl_detalle_inventario;
import clases.cl_inventario;
import clases.cl_varios;
import forms.frm_reg_inventario;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;
import models.m_moneda;

/**
 *
 * @author CONTABILIDAD 02
 */
public class frm_ver_inventarios extends javax.swing.JInternalFrame {

    cl_varios c_varios = new cl_varios();

    cl_inventario c_inventario = new cl_inventario();
    cl_detalle_inventario c_detalle = new cl_detalle_inventario();

    DefaultTableModel mostrar;
    int i;

    /**
     * Creates new form frm_ver_compra
     */
    public frm_ver_inventarios() {
        initComponents();
        c_inventario.cargar_periodos(cbx_periodo);
        c_detalle.mostrar_productos(t_detalle_inventario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_reg = new javax.swing.JButton();
        cbx_periodo = new javax.swing.JComboBox();
        btn_ver_inventario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_detalle_inventario = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        cbx_inventario = new javax.swing.JComboBox();
        txt_fecha = new javax.swing.JTextField();
        txt_usuario = new javax.swing.JTextField();

        setTitle("Listar Inventarios");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/find.png"))); // NOI18N
        jLabel1.setText("Buscar:");

        btn_reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/add.png"))); // NOI18N
        btn_reg.setText("Registrar");
        btn_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regActionPerformed(evt);
            }
        });

        cbx_periodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONAR PERIODO" }));
        cbx_periodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_periodoActionPerformed(evt);
            }
        });

        btn_ver_inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/clipboard_text.png"))); // NOI18N
        btn_ver_inventario.setText("Ver Reporte");
        btn_ver_inventario.setEnabled(false);
        btn_ver_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ver_inventarioActionPerformed(evt);
            }
        });

        t_detalle_inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_detalle_inventario.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        t_detalle_inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_detalle_inventarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t_detalle_inventario);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cancel.png"))); // NOI18N
        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/bin_closed.png"))); // NOI18N
        btn_eliminar.setText("Eliminar Inventario");
        btn_eliminar.setEnabled(false);
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        cbx_inventario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONAR INVENTARIO" }));
        cbx_inventario.setEnabled(false);
        cbx_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_inventarioActionPerformed(evt);
            }
        });

        txt_fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fecha.setText("Fecha");
        txt_fecha.setEnabled(false);

        txt_usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_usuario.setText("Usuario");
        txt_usuario.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 934, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_periodo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(cbx_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_ver_inventario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_reg))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_periodo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ver_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regActionPerformed
        frm_reg_inventario reg_inventario = new frm_reg_inventario();
        c_varios.llamar_ventana(reg_inventario);
        this.dispose();
    }//GEN-LAST:event_btn_regActionPerformed

    private void btn_ver_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ver_inventarioActionPerformed
        btn_eliminar.setEnabled(true);
        c_detalle.setInventario(cbx_inventario.getSelectedItem().toString());
        c_detalle.mostrar_productos(t_detalle_inventario);
    }//GEN-LAST:event_btn_ver_inventarioActionPerformed

    private void t_detalle_inventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_detalle_inventarioMouseClicked
        i = t_detalle_inventario.getSelectedRow();
        btn_ver_inventario.setEnabled(true);
        btn_eliminar.setEnabled(true);
    }//GEN-LAST:event_t_detalle_inventarioMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbx_periodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_periodoActionPerformed
        if (cbx_periodo.getSelectedIndex() > 0) {
            String periodo = cbx_periodo.getSelectedItem().toString();
            cbx_inventario.setEnabled(true);
            c_inventario.cargar_codigo(periodo, cbx_inventario);
            cbx_inventario.requestFocus();
        }
    }//GEN-LAST:event_cbx_periodoActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed

    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void cbx_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_inventarioActionPerformed
        if (cbx_inventario.getSelectedIndex() > 0) {
            c_inventario.setInventario(cbx_inventario.getSelectedItem().toString());
            c_inventario.cargar_datos();
            txt_usuario.setText(c_inventario.getUsuario());
            txt_fecha.setText(c_inventario.getFecha());
            btn_ver_inventario.setEnabled(true);
            btn_ver_inventario.requestFocus();
        }
    }//GEN-LAST:event_cbx_inventarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_reg;
    private javax.swing.JButton btn_ver_inventario;
    private javax.swing.JComboBox cbx_inventario;
    private javax.swing.JComboBox cbx_periodo;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t_detalle_inventario;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
