/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.cl_compra;
import clases.cl_moneda;
import clases.cl_pago_compras;
import clases.cl_proveedor;
import clases.cl_varios;
import forms.frm_reg_compra;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.m_moneda;

/**
 *
 * @author CONTABILIDAD 02
 */
public class frm_ver_compras extends javax.swing.JInternalFrame {

    cl_varios c_varios = new cl_varios();

    cl_compra c_compra = new cl_compra();
    cl_proveedor c_proveedor = new cl_proveedor();

    cl_pago_compras c_pagos = new cl_pago_compras();

    double total;

    DefaultTableModel mostrar;
    int i;
    int i_pagos;

    /**
     * Creates new form frm_ver_compra
     */
    public frm_ver_compras() {
        initComponents();
        String periodo = c_varios.obtener_periodo();
        String query = "select c.idcompra, c.periodo, c.fec_com, c.ruc_proveedor, p.raz_soc_pro, td.abreviado as documento, c.serie, c.numero, c.tc, m.corto, c.total, c.pagado, c.estado "
                + "from compras as c "
                + "inner join tipo_documento as td on c.idtido = td.id "
                + "inner join moneda as m on c.idmoneda = m.idmon "
                + "inner join proveedor as p on c.ruc_proveedor = p.ruc_pro "
                + "where c.periodo = '" + periodo + "' "
                + "order by c.periodo desc, c.idcompra desc";
        llenar_tabla(query);
    }

    private void llenar_tabla(String query) {
        total = c_compra.ver_compras(t_compras, query);
        txt_subtotal.setText(c_varios.formato_totales(total / 1.18));
        txt_igv.setText(c_varios.formato_totales(total / 1.18 * 0.18));
        txt_total.setText(c_varios.formato_totales(total));

        double total_deudas = 0;
        int c_filas = t_compras.getRowCount();
        for (int j = 0; j < c_filas; j++) {
            total_deudas = total_deudas + Double.parseDouble(t_compras.getValueAt(j, 6).toString());
        }
        txt_total_deudas.setText(c_varios.formato_totales(total_deudas));
    }

    private void mostrar_botones() {
        btn_pag.setEnabled(true);
        btn_eli.setEnabled(true);
        btn_detalle.setEnabled(true);
    }

    private void ocultar_botones() {
        btn_pag.setEnabled(false);
        btn_eli.setEnabled(false);
        btn_detalle.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_pagos = new javax.swing.JDialog();
        btn_del = new javax.swing.JButton();
        txt_mon = new javax.swing.JTextField();
        txt_tot = new javax.swing.JTextField();
        txt_documento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_fec = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_pen = new javax.swing.JTextField();
        txt_ruc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_raz = new javax.swing.JTextField();
        txt_pag = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_pagos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btn_reg1 = new javax.swing.JButton();
        lbl_periodo = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        jd_reg_pago = new javax.swing.JDialog();
        txt_fec_pago = new javax.swing.JFormattedTextField();
        cbx_mon_pago = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        txt_tc_pago = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_monto_pago = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbx_tipo_pago = new javax.swing.JComboBox();
        btn_cancelar_pago = new javax.swing.JButton();
        btn_grabar_pago = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_bus = new javax.swing.JTextField();
        btn_reg = new javax.swing.JButton();
        cbx_bus = new javax.swing.JComboBox();
        cbx_est = new javax.swing.JComboBox();
        btn_pag = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_compras = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_subtotal = new javax.swing.JTextField();
        btn_eli = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_igv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_total_deudas = new javax.swing.JTextField();
        btn_detalle = new javax.swing.JButton();

        jd_pagos.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jd_pagos.setTitle("Ver Pagos del Documento de Compra");

        btn_del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/bin_closed.png"))); // NOI18N
        btn_del.setText("Eliminar");
        btn_del.setEnabled(false);
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });

        txt_mon.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_mon.setEnabled(false);

        txt_tot.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_tot.setEnabled(false);

        txt_documento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_documento.setEnabled(false);

        jLabel5.setText("Fecha Doc");

        jLabel6.setText("Moneda:");

        try {
            txt_fec.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_fec.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fec.setEnabled(false);

        jLabel7.setText("Total:");

        jLabel8.setText("Pendiente:");

        jLabel9.setText("Proveedor:");

        txt_pen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_pen.setEnabled(false);

        txt_ruc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ruc.setEnabled(false);

        jLabel10.setText("Pagado");

        txt_raz.setEnabled(false);

        txt_pag.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_pag.setEnabled(false);

        jLabel11.setText("Documento");

        t_pagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_pagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_pagosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(t_pagos);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cancel.png"))); // NOI18N
        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_reg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/add.png"))); // NOI18N
        btn_reg1.setText("+Pago");
        btn_reg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg1ActionPerformed(evt);
            }
        });

        lbl_periodo.setText("periodo");

        lbl_id.setText("id");

        javax.swing.GroupLayout jd_pagosLayout = new javax.swing.GroupLayout(jd_pagos.getContentPane());
        jd_pagos.getContentPane().setLayout(jd_pagosLayout);
        jd_pagosLayout.setHorizontalGroup(
            jd_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_pagosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jd_pagosLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ruc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_raz))
                    .addGroup(jd_pagosLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_fec, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_id)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_periodo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_reg1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_pagosLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_mon, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tot, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_pag, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_pen, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 27, Short.MAX_VALUE)
                        .addComponent(btn_del)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jd_pagosLayout.setVerticalGroup(
            jd_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_pagosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ruc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_raz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reg1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_periodo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tot, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pag, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jd_reg_pago.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jd_reg_pago.setTitle("Guardar Pago a Proveedor");

        try {
            txt_fec_pago.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_fec_pago.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fec_pago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_fec_pagoKeyPressed(evt);
            }
        });

        cbx_mon_pago.setEnabled(false);
        cbx_mon_pago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_mon_pagoKeyPressed(evt);
            }
        });

        jLabel12.setText("Moneda:");

        txt_tc_pago.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_tc_pago.setEnabled(false);
        txt_tc_pago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_tc_pagoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_tc_pagoKeyTyped(evt);
            }
        });

        jLabel13.setText("Pago a Realizar:");
        jLabel13.setFocusable(false);

        jLabel14.setText("Fecha:");
        jLabel14.setFocusable(false);

        txt_monto_pago.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_monto_pago.setEnabled(false);
        txt_monto_pago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_monto_pagoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_monto_pagoKeyTyped(evt);
            }
        });

        jLabel15.setText("Tipo de Cambio");

        jLabel16.setText("Tipo de Pago");

        cbx_tipo_pago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EFECTIVO" }));
        cbx_tipo_pago.setEnabled(false);
        cbx_tipo_pago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_tipo_pagoKeyPressed(evt);
            }
        });

        btn_cancelar_pago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cancel.png"))); // NOI18N
        btn_cancelar_pago.setText("Cancelar");
        btn_cancelar_pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar_pagoActionPerformed(evt);
            }
        });

        btn_grabar_pago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/add.png"))); // NOI18N
        btn_grabar_pago.setText("Grabar");
        btn_grabar_pago.setEnabled(false);
        btn_grabar_pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_grabar_pagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_reg_pagoLayout = new javax.swing.GroupLayout(jd_reg_pago.getContentPane());
        jd_reg_pago.getContentPane().setLayout(jd_reg_pagoLayout);
        jd_reg_pagoLayout.setHorizontalGroup(
            jd_reg_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_reg_pagoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_reg_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_reg_pagoLayout.createSequentialGroup()
                        .addGroup(jd_reg_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_reg_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_reg_pagoLayout.createSequentialGroup()
                                .addComponent(txt_monto_pago)
                                .addGap(152, 152, 152))
                            .addGroup(jd_reg_pagoLayout.createSequentialGroup()
                                .addGroup(jd_reg_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jd_reg_pagoLayout.createSequentialGroup()
                                        .addComponent(btn_grabar_pago)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_cancelar_pago))
                                    .addGroup(jd_reg_pagoLayout.createSequentialGroup()
                                        .addGroup(jd_reg_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_tc_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbx_mon_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_fec_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(78, 78, 78))
                                    .addComponent(cbx_tipo_pago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(jd_reg_pagoLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jd_reg_pagoLayout.setVerticalGroup(
            jd_reg_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_reg_pagoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_reg_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_fec_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_reg_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_mon_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_reg_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tc_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_reg_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_tipo_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_reg_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_monto_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_reg_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_grabar_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setTitle("Listar Registro de Compras");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/find.png"))); // NOI18N
        jLabel1.setText("Buscar:");

        txt_bus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_busKeyPressed(evt);
            }
        });

        btn_reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/add.png"))); // NOI18N
        btn_reg.setText("Registrar");
        btn_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regActionPerformed(evt);
            }
        });

        cbx_bus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PROVEEDOR", "PERIODO", "DOCUMENTO" }));
        cbx_bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_busActionPerformed(evt);
            }
        });

        cbx_est.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PAGADO", "PENDIENTE", "TODOS" }));
        cbx_est.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_estActionPerformed(evt);
            }
        });

        btn_pag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/clipboard_text.png"))); // NOI18N
        btn_pag.setText("Ver Pagos");
        btn_pag.setEnabled(false);
        btn_pag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pagActionPerformed(evt);
            }
        });

        t_compras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_compras.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        t_compras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_comprasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t_compras);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cancel.png"))); // NOI18N
        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("SUB Total:");

        txt_subtotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_subtotal.setFocusable(false);

        btn_eli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/bin_closed.png"))); // NOI18N
        btn_eli.setText("Eliminar Compra");
        btn_eli.setEnabled(false);
        btn_eli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliActionPerformed(evt);
            }
        });

        jLabel3.setText("IGV");

        txt_igv.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_igv.setFocusable(false);

        jLabel4.setText("Total");

        txt_total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_total.setFocusable(false);

        jLabel17.setText("Total Deuda");

        txt_total_deudas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_total_deudas.setFocusable(false);

        btn_detalle.setText("Ver Detalle");
        btn_detalle.setEnabled(false);
        btn_detalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detalleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_bus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_detalle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_est, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_pag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_reg))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_igv, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btn_eli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_total_deudas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_est, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pag, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_detalle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_eli, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_total_deudas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_igv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regActionPerformed
        frm_reg_compra reg_compra = new frm_reg_compra();
        c_varios.llamar_ventana(reg_compra);
        this.dispose();
    }//GEN-LAST:event_btn_regActionPerformed

    private void btn_pagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pagActionPerformed
        if (i > -1) {
            ocultar_botones();

            c_compra.setCod_compra(t_compras.getValueAt(i, 0).toString());
            c_compra.datos_compra();
            c_proveedor.setRuc(c_compra.getProveedor());
            c_proveedor.cargar_datos_proveedor();

            jd_pagos.setModal(true);
            jd_pagos.setSize(700, 388);
            jd_pagos.setLocationRelativeTo(null);

            txt_ruc.setText(c_proveedor.getRuc());
            txt_raz.setText(c_proveedor.getRazon_social());
            txt_documento.setText(t_compras.getValueAt(i, 2).toString());
            txt_fec.setText(t_compras.getValueAt(i, 1).toString());

            txt_mon.setText(t_compras.getValueAt(i, 4).toString());
            txt_tot.setText(c_varios.formato_totales(c_compra.getTotal()));

            c_pagos.setPeriodo(c_compra.getPeriodo());
            c_pagos.setCompra(c_compra.getCodigo());
            double pagado = c_pagos.mostrar_pagos(t_pagos);

            txt_pag.setText(c_varios.formato_totales(pagado));
            txt_pen.setText(c_varios.formato_totales(c_compra.getTotal() - pagado));

            jd_pagos.setVisible(true);
        }
    }//GEN-LAST:event_btn_pagActionPerformed

    private void t_comprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_comprasMouseClicked
        i = t_compras.getSelectedRow();

        if (evt.getClickCount() == 2) {
            mostrar_botones();
        }
    }//GEN-LAST:event_t_comprasMouseClicked

    private void txt_busKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String busqueda = txt_bus.getText().trim();
            String query = null;
            if (cbx_bus.getSelectedIndex() == 0) {
                query = "select c.idcompra, c.periodo, c.fec_com, c.ruc_proveedor, p.raz_soc_pro, td.abreviado as documento, c.serie, c.numero, c.tc, m.corto, c.total, c.pagado, c.estado "
                        + "from compras as c "
                        + "inner join tipo_documento as td on c.idtido = td.id "
                        + "inner join moneda as m on c.idmoneda = m.idmon "
                        + "inner join proveedor as p on c.ruc_proveedor = p.ruc_pro "
                        + "where c.ruc_proveedor like '%" + busqueda + "%' or p.raz_soc_pro like '%" + busqueda + "%' "
                        + "order by c.periodo desc, c.idcompra desc";
            }
            if (cbx_bus.getSelectedIndex() == 1) {
                query = "select c.idcompra, c.periodo, c.fec_com, c.ruc_proveedor, p.raz_soc_pro, td.abreviado as documento, c.serie, c.numero, c.tc, m.corto, c.total, c.pagado, c.estado "
                        + "from compras as c "
                        + "inner join tipo_documento as td on c.idtido = td.id "
                        + "inner join moneda as m on c.idmoneda = m.idmon "
                        + "inner join proveedor as p on c.ruc_proveedor = p.ruc_pro "
                        + "where c.periodo = '" + busqueda + "' "
                        + "order by c.periodo desc, c.idcompra desc";
            }
            if (cbx_bus.getSelectedIndex() == 2) {
                query = "select c.idcompra, c.periodo, c.fec_com, c.ruc_proveedor, p.raz_soc_pro, td.abreviado as documento, c.serie, c.numero, c.tc, m.corto, c.total, c.pagado, c.estado "
                        + "from compras as c "
                        + "inner join tipo_documento as td on c.idtido = td.id "
                        + "inner join moneda as m on c.idmoneda = m.idmon "
                        + "inner join proveedor as p on c.ruc_proveedor = p.ruc_pro "
                        + "where c.numero like '%" + busqueda + "%' "
                        + "order by c.periodo desc, c.idcompra desc";
            }
            llenar_tabla(query);
        }
    }//GEN-LAST:event_txt_busKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbx_estActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_estActionPerformed
        String query = "";
        if (cbx_est.getSelectedIndex() == 0) {
            query = "select c.idcompra, c.periodo, c.fec_com, c.ruc_proveedor, p.raz_soc_pro, td.abreviado as documento, c.serie, c.numero, c.tc, m.corto, c.total, c.pagado, c.estado "
                    + "from compras as c "
                    + "inner join tipo_documento as td on c.idtido = td.id "
                    + "inner join moneda as m on c.idmoneda = m.idmon "
                    + "inner join proveedor as p on c.ruc_proveedor = p.ruc_pro "
                    + "where c.estado = 1 "
                    + "order by c.periodo desc, c.idcompra desc";

        }
        if (cbx_est.getSelectedIndex() == 1) {
            query = "select c.idcompra, c.periodo, c.fec_com, c.ruc_proveedor, p.raz_soc_pro, td.abreviado as documento, c.serie, c.numero, c.tc, m.corto, c.total, c.pagado, c.estado "
                    + "from compras as c "
                    + "inner join tipo_documento as td on c.idtido = td.id "
                    + "inner join moneda as m on c.idmoneda = m.idmon "
                    + "inner join proveedor as p on c.ruc_proveedor = p.ruc_pro "
                    + "where c.estado = 0 "
                    + "order by c.periodo desc, c.idcompra desc";

        }
        if (cbx_est.getSelectedIndex() == 2) {
            query = "select c.idcompra, c.periodo, c.fec_com, c.ruc_proveedor, p.raz_soc_pro, td.abreviado as documento, c.serie, c.numero, c.tc, m.corto, c.total, c.pagado, c.estado "
                    + "from compras as c "
                    + "inner join tipo_documento as td on c.idtido = td.id "
                    + "inner join moneda as m on c.idmoneda = m.idmon "
                    + "inner join proveedor as p on c.ruc_proveedor = p.ruc_pro "
                    + "order by c.periodo desc, c.idcompra desc";

        }
        llenar_tabla(query);
    }//GEN-LAST:event_cbx_estActionPerformed

    private void btn_eliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliActionPerformed
        ocultar_botones();
        if (i > -1) {
            //eliminar compra 
            c_compra.setCod_compra(t_compras.getValueAt(i, 0).toString());
            c_compra.eliminar();
            String periodo = c_varios.obtener_periodo();
            String query = "select c.idcompra, c.periodo, c.fec_com, c.ruc_proveedor, p.raz_soc_pro, td.abreviado as documento, c.serie, c.numero, c.tc, m.corto, c.total, c.pagado, c.estado "
                    + "from compras as c "
                    + "inner join tipo_documento as td on c.idtido = td.id "
                    + "inner join moneda as m on c.idmoneda = m.idmon "
                    + "inner join proveedor as p on c.ruc_proveedor = p.ruc_pro "
                    + "where c.periodo = '" + periodo + "' "
                    + "order by c.periodo desc, c.idcompra desc";
            llenar_tabla(query);
        }
    }//GEN-LAST:event_btn_eliActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        c_pagos.setPeriodo(c_compra.getPeriodo());
        c_pagos.setCompra(c_compra.getCodigo());
        c_pagos.setCodigo(Integer.parseInt(t_pagos.getValueAt(i_pagos, 0).toString()));
        if (c_pagos.eliminar()) {
            double pagado = c_pagos.mostrar_pagos(t_pagos);
            txt_pag.setText(c_varios.formato_totales(pagado));
            txt_pen.setText(c_varios.formato_totales(c_compra.getTotal() - pagado));
        }
        btn_del.setEnabled(false);
    }//GEN-LAST:event_btn_delActionPerformed

    private void t_pagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_pagosMouseClicked
        i_pagos = t_pagos.getSelectedRow();
        btn_del.setEnabled(true);
    }//GEN-LAST:event_t_pagosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jd_pagos.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_reg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg1ActionPerformed
        m_moneda m_moneda = new m_moneda();

        jd_reg_pago.setModal(true);
        jd_reg_pago.setSize(390, 262);
        jd_reg_pago.setLocationRelativeTo(null);

        m_moneda.cbx_moneda(cbx_mon_pago);
        txt_fec_pago.setText(c_varios.formato_fecha_vista(c_varios.getFechaActual()));

        jd_reg_pago.setVisible(true);
    }//GEN-LAST:event_btn_reg1ActionPerformed

    private void txt_tc_pagoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tc_pagoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_tc_pago.getText().length() == 5) {
                cbx_tipo_pago.setEnabled(true);
                cbx_tipo_pago.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_tc_pagoKeyPressed

    private void txt_monto_pagoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_monto_pagoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btn_grabar_pago.setEnabled(true);
            btn_grabar_pago.requestFocus();
        }
    }//GEN-LAST:event_txt_monto_pagoKeyPressed

    private void txt_monto_pagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_monto_pagoKeyTyped
        c_varios.solo_precio(evt);
        c_varios.limitar_caracteres(evt, txt_monto_pago, 8);
    }//GEN-LAST:event_txt_monto_pagoKeyTyped

    private void cbx_tipo_pagoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_tipo_pagoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_monto_pago.setEnabled(true);
            txt_monto_pago.requestFocus();
        }
    }//GEN-LAST:event_cbx_tipo_pagoKeyPressed

    private void btn_cancelar_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar_pagoActionPerformed
        jd_reg_pago.dispose();
    }//GEN-LAST:event_btn_cancelar_pagoActionPerformed

    private void btn_grabar_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_grabar_pagoActionPerformed
        btn_grabar_pago.setEnabled(true);
        cl_moneda c_moneda = (cl_moneda) cbx_mon_pago.getSelectedItem();
        int id_moneda = c_moneda.getCodigo();

        c_pagos.setCodigo(c_pagos.obtener_codigo());
        c_pagos.setCompra(c_compra.getCodigo());
        c_pagos.setPeriodo(c_compra.getPeriodo());
        c_pagos.setFecha(c_varios.formato_fecha_mysql(txt_fec_pago.getText()));
        c_pagos.setMonto(Double.parseDouble(txt_monto_pago.getText()));
        c_pagos.setTc(Double.parseDouble(txt_tc_pago.getText()));
        c_pagos.setTipo(cbx_tipo_pago.getSelectedIndex() + 1);
        c_pagos.setMoneda(id_moneda);

        if (c_pagos.insertar()) {
            double pagado = c_pagos.mostrar_pagos(t_pagos);
            txt_pag.setText(c_varios.formato_totales(pagado));
            txt_pen.setText(c_varios.formato_totales(c_compra.getTotal() - pagado));
            jd_reg_pago.dispose();
        }
    }//GEN-LAST:event_btn_grabar_pagoActionPerformed

    private void txt_fec_pagoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fec_pagoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_fec_pago.getText().length() == 10) {
                cbx_mon_pago.setEnabled(true);
                cbx_mon_pago.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_fec_pagoKeyPressed

    private void cbx_mon_pagoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_mon_pagoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cl_moneda c_moneda = (cl_moneda) cbx_mon_pago.getSelectedItem();
            int id_moneda = c_moneda.getCodigo();

            if (id_moneda == c_compra.getMoneda()) {
                txt_tc_pago.setText("1.000");
                txt_tc_pago.setEnabled(false);
                cbx_tipo_pago.setEnabled(true);
                cbx_tipo_pago.requestFocus();

            } else {
                txt_tc_pago.setText("");
                txt_tc_pago.setEnabled(true);
                txt_tc_pago.requestFocus();
            }
        }
    }//GEN-LAST:event_cbx_mon_pagoKeyPressed

    private void txt_tc_pagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tc_pagoKeyTyped
        c_varios.solo_precio(evt);
        c_varios.limitar_caracteres(evt, txt_tc_pago, 5);
    }//GEN-LAST:event_txt_tc_pagoKeyTyped

    private void cbx_busActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_busActionPerformed
        txt_bus.setText("");
        txt_bus.requestFocus();
    }//GEN-LAST:event_cbx_busActionPerformed

    private void btn_detalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detalleActionPerformed
        ocultar_botones();

        Frame f = JOptionPane.getRootFrame();
        frm_ver_datos_compra.c_compra.setCod_compra(t_compras.getValueAt(i, 0).toString());
        frm_ver_datos_compra dialog = new frm_ver_datos_compra(f, true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_btn_detalleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar_pago;
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_detalle;
    private javax.swing.JButton btn_eli;
    private javax.swing.JButton btn_grabar_pago;
    private javax.swing.JButton btn_pag;
    private javax.swing.JButton btn_reg;
    public static javax.swing.JButton btn_reg1;
    private javax.swing.JComboBox cbx_bus;
    private javax.swing.JComboBox cbx_est;
    public static javax.swing.JComboBox cbx_mon_pago;
    public static javax.swing.JComboBox cbx_tipo_pago;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog jd_pagos;
    private javax.swing.JDialog jd_reg_pago;
    public static javax.swing.JLabel lbl_id;
    public static javax.swing.JLabel lbl_periodo;
    private javax.swing.JTable t_compras;
    public static javax.swing.JTable t_pagos;
    private javax.swing.JTextField txt_bus;
    public static javax.swing.JTextField txt_documento;
    public static javax.swing.JFormattedTextField txt_fec;
    public static javax.swing.JFormattedTextField txt_fec_pago;
    private javax.swing.JTextField txt_igv;
    public static javax.swing.JTextField txt_mon;
    public static javax.swing.JTextField txt_monto_pago;
    public static javax.swing.JTextField txt_pag;
    public static javax.swing.JTextField txt_pen;
    public static javax.swing.JTextField txt_raz;
    public static javax.swing.JTextField txt_ruc;
    private javax.swing.JTextField txt_subtotal;
    private javax.swing.JTextField txt_tc_pago;
    public static javax.swing.JTextField txt_tot;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_total_deudas;
    // End of variables declaration//GEN-END:variables
}
