/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.cl_cobro_ventas;
import clases.cl_detalle_venta;
import clases.cl_varios;
import clases.cl_venta;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author CONTABILIDAD 02
 */
public class frm_ver_ventas extends javax.swing.JInternalFrame {

    cl_varios c_varios = new cl_varios();

    cl_venta c_venta = new cl_venta();
    cl_cobro_ventas c_cobros = new cl_cobro_ventas();
    cl_detalle_venta c_detalle = new cl_detalle_venta();

    int fila_seleccionada = -1;
    int fila_pago = -1;

    /**
     * Creates new form frm_ver_cobranzas
     */
    public frm_ver_ventas() {
        initComponents();
        cargar_tabla();

    }

    private void cargar_tabla() {
        String query = "select v.periodo, v.id, v.nro_placa, v.fecha_venta, td.abreviado as documento, v.serie_doc, v.nro_doc, c.documento as doc_cliente, v.nombre_cliente, v.kilometraje, v.total, v.descuento, v.pagado, v.estado "
                + "from ventas as v "
                + "inner join tipo_documento as td on td.id = v.tipo_documento "
                + "inner join clientes as c on c.codigo = v.cliente "
                + "where v.fecha_venta = '" + c_varios.getFechaActual() + "' "
                + "order by v.id asc";
        double total = c_venta.ver_ventas(t_ventas, query);
        txt_tot.setText(c_varios.formato_totales(total));
        cbx_busqueda.setSelectedIndex(0);
        txt_total_deudas.setText(c_varios.formato_totales(deudas_ventas()));
        txt_bus.requestFocus();
    }

    private double deudas_ventas() {
        double deudas = 0;
        int nro_filas = t_ventas.getRowCount();
        for (int i = 0; i < nro_filas; i++) {
            deudas = deudas + Double.parseDouble(t_ventas.getValueAt(i, 6).toString());
        }
        return deudas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_ver_pagos = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_jd_cliente = new javax.swing.JTextField();
        txt_jd_iventa = new javax.swing.JTextField();
        txt_jd_placa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_jd_numero = new javax.swing.JTextField();
        txt_jd_porcobrar = new javax.swing.JTextField();
        txt_jd_total = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_jd_pagos = new javax.swing.JTable();
        btn_jd_cerrar = new javax.swing.JButton();
        btn_jd_registrar = new javax.swing.JButton();
        btn_jd_eliminar_pago = new javax.swing.JButton();
        txt_jd_moneda = new javax.swing.JTextField();
        jd_ver_detalle_venta = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        t_detalle = new javax.swing.JTable();
        btn_detalle_cerrar = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        txt_detalle_total = new javax.swing.JTextField();
        txt_jd_numero1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_jd_placa1 = new javax.swing.JTextField();
        txt_jd_iventa1 = new javax.swing.JTextField();
        txt_jd_cliente1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_jd_moneda1 = new javax.swing.JTextField();
        txt_jd_total1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jd_reg_pago = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_jda_fecha = new javax.swing.JFormattedTextField();
        cbx_jda_tipopago = new javax.swing.JComboBox();
        txt_jda_monto = new javax.swing.JTextField();
        btn_jda_registrar = new javax.swing.JButton();
        jd_modificar_venta = new javax.swing.JDialog();
        jLabel28 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_modificar_placa = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txt_modificar_cliente = new javax.swing.JTextField();
        txt_modificar_fecha = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        txt_modificar_documento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_modificar_kilometraje = new javax.swing.JTextField();
        btn_modificar_guardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_bus = new javax.swing.JTextField();
        cbx_busqueda = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_ventas = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_tot = new javax.swing.JTextField();
        btn_anu = new javax.swing.JButton();
        cbx_estado = new javax.swing.JComboBox();
        btn_ver_detalle = new javax.swing.JButton();
        btn_ver_cobro = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_total_deudas = new javax.swing.JTextField();

        jd_ver_pagos.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jd_ver_pagos.setTitle("Detalle de Pagos");
        jd_ver_pagos.setResizable(false);

        jLabel3.setText("Cliente:");

        jLabel4.setText("Placa:");

        jLabel5.setText("IdVenta");

        txt_jd_cliente.setEnabled(false);

        txt_jd_iventa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_jd_iventa.setEnabled(false);

        txt_jd_placa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_jd_placa.setEnabled(false);

        jLabel7.setText("Moneda:");

        jLabel8.setText("Tipo de Documento:");

        jLabel11.setText("Total:");

        jLabel14.setText("Por Cobrar:");

        txt_jd_numero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_jd_numero.setEnabled(false);

        txt_jd_porcobrar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_jd_porcobrar.setEnabled(false);

        txt_jd_total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_jd_total.setEnabled(false);

        t_jd_pagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_jd_pagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_jd_pagosMouseClicked(evt);
            }
        });
        t_jd_pagos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_jd_pagosKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(t_jd_pagos);

        btn_jd_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cancel.png"))); // NOI18N
        btn_jd_cerrar.setText("Cerrar");
        btn_jd_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jd_cerrarActionPerformed(evt);
            }
        });

        btn_jd_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/add.png"))); // NOI18N
        btn_jd_registrar.setText("Registrar");
        btn_jd_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jd_registrarActionPerformed(evt);
            }
        });

        btn_jd_eliminar_pago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/bin_closed.png"))); // NOI18N
        btn_jd_eliminar_pago.setText("Eliminar Pago");
        btn_jd_eliminar_pago.setEnabled(false);
        btn_jd_eliminar_pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jd_eliminar_pagoActionPerformed(evt);
            }
        });

        txt_jd_moneda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_jd_moneda.setText("S/   - NUEVO SOL");
        txt_jd_moneda.setEnabled(false);

        javax.swing.GroupLayout jd_ver_pagosLayout = new javax.swing.GroupLayout(jd_ver_pagos.getContentPane());
        jd_ver_pagos.getContentPane().setLayout(jd_ver_pagosLayout);
        jd_ver_pagosLayout.setHorizontalGroup(
            jd_ver_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ver_pagosLayout.createSequentialGroup()
                .addGroup(jd_ver_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ver_pagosLayout.createSequentialGroup()
                        .addGroup(jd_ver_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_ver_pagosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jd_ver_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)))
                            .addGroup(jd_ver_pagosLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7))
                            .addGroup(jd_ver_pagosLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel11)))
                        .addGap(25, 25, 25)
                        .addGroup(jd_ver_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_ver_pagosLayout.createSequentialGroup()
                                .addGroup(jd_ver_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_jd_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_jd_moneda, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jd_ver_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_ver_pagosLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_jd_iventa, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jd_ver_pagosLayout.createSequentialGroup()
                                        .addGroup(jd_ver_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel14))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jd_ver_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jd_ver_pagosLayout.createSequentialGroup()
                                                .addComponent(txt_jd_porcobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 118, Short.MAX_VALUE))
                                            .addComponent(txt_jd_numero)))))
                            .addComponent(txt_jd_cliente)
                            .addGroup(jd_ver_pagosLayout.createSequentialGroup()
                                .addComponent(txt_jd_total, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 420, Short.MAX_VALUE)))
                        .addGap(0, 86, Short.MAX_VALUE))
                    .addGroup(jd_ver_pagosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_ver_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ver_pagosLayout.createSequentialGroup()
                                .addComponent(btn_jd_registrar)
                                .addGap(48, 48, 48)
                                .addComponent(btn_jd_eliminar_pago)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_jd_cerrar)))))
                .addContainerGap())
        );
        jd_ver_pagosLayout.setVerticalGroup(
            jd_ver_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ver_pagosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_ver_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jd_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ver_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jd_iventa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jd_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ver_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jd_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jd_moneda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ver_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jd_porcobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jd_total, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ver_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_jd_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_jd_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_jd_eliminar_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jd_ver_detalle_venta.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jd_ver_detalle_venta.setTitle("Detalle de Venta");

        t_detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_detalle.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(t_detalle);

        btn_detalle_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cancel.png"))); // NOI18N
        btn_detalle_cerrar.setText("Cerrar");
        btn_detalle_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detalle_cerrarActionPerformed(evt);
            }
        });

        jLabel25.setText("total:");

        txt_detalle_total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_detalle_total.setEnabled(false);

        txt_jd_numero1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_jd_numero1.setEnabled(false);

        jLabel12.setText("Total:");

        jLabel10.setText("Tipo de Documento:");

        jLabel13.setText("Moneda:");

        txt_jd_placa1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_jd_placa1.setEnabled(false);

        txt_jd_iventa1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_jd_iventa1.setEnabled(false);

        txt_jd_cliente1.setEnabled(false);

        jLabel18.setText("IdVenta");

        txt_jd_moneda1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_jd_moneda1.setText("S/   - NUEVO SOL");
        txt_jd_moneda1.setEnabled(false);

        txt_jd_total1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_jd_total1.setEnabled(false);

        jLabel22.setText("Cliente:");

        jLabel30.setText("Placa:");

        javax.swing.GroupLayout jd_ver_detalle_ventaLayout = new javax.swing.GroupLayout(jd_ver_detalle_venta.getContentPane());
        jd_ver_detalle_venta.getContentPane().setLayout(jd_ver_detalle_ventaLayout);
        jd_ver_detalle_ventaLayout.setHorizontalGroup(
            jd_ver_detalle_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ver_detalle_ventaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_ver_detalle_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                    .addGroup(jd_ver_detalle_ventaLayout.createSequentialGroup()
                        .addComponent(btn_detalle_cerrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_detalle_total, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_ver_detalle_ventaLayout.createSequentialGroup()
                        .addGroup(jd_ver_detalle_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel30)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGap(25, 25, 25)
                        .addGroup(jd_ver_detalle_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_ver_detalle_ventaLayout.createSequentialGroup()
                                .addGroup(jd_ver_detalle_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_jd_placa1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_jd_moneda1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jd_ver_detalle_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_ver_detalle_ventaLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_jd_iventa1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jd_ver_detalle_ventaLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_jd_numero1))))
                            .addComponent(txt_jd_cliente1)
                            .addGroup(jd_ver_detalle_ventaLayout.createSequentialGroup()
                                .addComponent(txt_jd_total1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 420, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jd_ver_detalle_ventaLayout.setVerticalGroup(
            jd_ver_detalle_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ver_detalle_ventaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_ver_detalle_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jd_cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ver_detalle_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jd_iventa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jd_placa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ver_detalle_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jd_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jd_moneda1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ver_detalle_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jd_total1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ver_detalle_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_detalle_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_detalle_total, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jd_reg_pago.setTitle("Registrar Cobro de Venta");

        jLabel15.setText("Fecha:");

        jLabel16.setText("Tipo de Pago:");

        jLabel19.setText("Monto:");

        try {
            txt_jda_fecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_jda_fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_jda_fecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_jda_fechaKeyPressed(evt);
            }
        });

        cbx_jda_tipopago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EFECTIVO" }));
        cbx_jda_tipopago.setEnabled(false);
        cbx_jda_tipopago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_jda_tipopagoKeyPressed(evt);
            }
        });

        txt_jda_monto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_jda_monto.setEnabled(false);
        txt_jda_monto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_jda_montoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_jda_montoKeyTyped(evt);
            }
        });

        btn_jda_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/add.png"))); // NOI18N
        btn_jda_registrar.setText("Registrar");
        btn_jda_registrar.setEnabled(false);
        btn_jda_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jda_registrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_reg_pagoLayout = new javax.swing.GroupLayout(jd_reg_pago.getContentPane());
        jd_reg_pago.getContentPane().setLayout(jd_reg_pagoLayout);
        jd_reg_pagoLayout.setHorizontalGroup(
            jd_reg_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_reg_pagoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_reg_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19))
                .addGap(28, 28, 28)
                .addGroup(jd_reg_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_jda_monto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jda_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_jda_tipopago, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_reg_pagoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_jda_registrar)
                .addContainerGap())
        );
        jd_reg_pagoLayout.setVerticalGroup(
            jd_reg_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_reg_pagoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_reg_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jda_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_reg_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_jda_tipopago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_reg_pagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jda_monto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_jda_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jd_modificar_venta.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jd_modificar_venta.setTitle("Modificar Venta");
        jd_modificar_venta.setResizable(false);

        jLabel28.setText("Placa");

        jLabel21.setText("Tipo de Documento");

        txt_modificar_placa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_modificar_placa.setEnabled(false);

        jLabel29.setText("Cliente:");

        txt_modificar_cliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_modificar_cliente.setEnabled(false);

        try {
            txt_modificar_fecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_modificar_fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_modificar_fecha.setEnabled(false);

        jLabel24.setText("Fecha:");

        txt_modificar_documento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_modificar_documento.setEnabled(false);

        jLabel6.setText("Kilometraje:");

        txt_modificar_kilometraje.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btn_modificar_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/application_edit.png"))); // NOI18N
        btn_modificar_guardar.setText("Modificar");
        btn_modificar_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificar_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_modificar_ventaLayout = new javax.swing.GroupLayout(jd_modificar_venta.getContentPane());
        jd_modificar_venta.getContentPane().setLayout(jd_modificar_ventaLayout);
        jd_modificar_ventaLayout.setHorizontalGroup(
            jd_modificar_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificar_ventaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_modificar_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel28)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jd_modificar_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modificar_ventaLayout.createSequentialGroup()
                        .addComponent(txt_modificar_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addComponent(txt_modificar_cliente))
                    .addGroup(jd_modificar_ventaLayout.createSequentialGroup()
                        .addComponent(txt_modificar_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_modificar_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_modificar_ventaLayout.createSequentialGroup()
                        .addComponent(txt_modificar_kilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_modificar_guardar)))
                .addContainerGap())
        );
        jd_modificar_ventaLayout.setVerticalGroup(
            jd_modificar_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificar_ventaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_modificar_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_modificar_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_modificar_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_modificar_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txt_modificar_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(txt_modificar_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_modificar_ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_modificar_kilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_modificar_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setTitle("Registro de Ventas");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/find.png"))); // NOI18N
        jLabel1.setText("Buscar");

        txt_bus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_busKeyPressed(evt);
            }
        });

        cbx_busqueda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FECHA", "CLIENTE", "VEHICULO", "NRO. BOLETA / FACTURA" }));
        cbx_busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_busquedaActionPerformed(evt);
            }
        });

        t_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_ventasMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t_ventasMousePressed(evt);
            }
        });
        t_ventas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_ventasKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(t_ventas);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cancel.png"))); // NOI18N
        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Total:");

        txt_tot.setEditable(false);
        txt_tot.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btn_anu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/bin_closed.png"))); // NOI18N
        btn_anu.setText("Anular");
        btn_anu.setEnabled(false);
        btn_anu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anuActionPerformed(evt);
            }
        });

        cbx_estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PAGADOS", "POR COBRAR", "ANULADOS", "TODOS" }));
        cbx_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_estadoActionPerformed(evt);
            }
        });

        btn_ver_detalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/clipboard_text.png"))); // NOI18N
        btn_ver_detalle.setText("Ver Detalle");
        btn_ver_detalle.setEnabled(false);
        btn_ver_detalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ver_detalleActionPerformed(evt);
            }
        });

        btn_ver_cobro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/clipboard_text.png"))); // NOI18N
        btn_ver_cobro.setText("Ver Pagos");
        btn_ver_cobro.setEnabled(false);
        btn_ver_cobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ver_cobroActionPerformed(evt);
            }
        });

        btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/application_edit.png"))); // NOI18N
        btn_modificar.setText("Modificar");
        btn_modificar.setEnabled(false);
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        jLabel9.setText("TOTAL DEUDAS:");

        txt_total_deudas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_total_deudas.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ver_cobro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ver_detalle))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_tot, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_anu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txt_total_deudas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbx_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbx_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_ver_detalle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_ver_cobro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tot, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_anu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txt_total_deudas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private double total() {
        Double tot = 0.0;
        int nro_fila = t_ventas.getRowCount();
        if (nro_fila > 0) {
            for (int j = 0; j < nro_fila; j++) {
                tot = tot + Double.parseDouble(t_ventas.getValueAt(j, 9).toString());
            }
        }
        return tot;
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbx_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_busquedaActionPerformed
        txt_bus.setText("");
        txt_bus.requestFocus();
    }//GEN-LAST:event_cbx_busquedaActionPerformed

    private void txt_busKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String query = "";
            String busqueda = txt_bus.getText().trim();
            if (busqueda.length() > 0) {
                if (cbx_busqueda.getSelectedIndex() == 0) {
                    if (busqueda.length() == 10) {
                        busqueda = c_varios.formato_fecha_mysql(busqueda);
                        query = "select v.periodo, v.id, v.nro_placa, v.fecha_venta, td.abreviado as documento, v.serie_doc, v.nro_doc, c.documento as doc_cliente, v.nombre_cliente, v.kilometraje, v.total, v.descuento, v.pagado, v.estado "
                                + "from ventas as v "
                                + "inner join tipo_documento as td on td.id = v.tipo_documento "
                                + "inner join clientes as c on c.codigo = v.cliente "
                                + "where v.fecha_venta = '" + busqueda + "'";
                        System.out.println(query);
                    } else {
                        JOptionPane.showMessageDialog(null, "FECHA INCORRECTA");
                    }
                }
                if (cbx_busqueda.getSelectedIndex() == 1) {
                    query = "select v.periodo, v.id, v.nro_placa, v.fecha_venta, td.abreviado as documento, v.serie_doc, v.nro_doc, c.documento as doc_cliente, v.nombre_cliente, v.kilometraje, v.total, v.descuento, v.pagado, v.estado "
                            + "from ventas as v "
                            + "inner join tipo_documento as td on td.id = v.tipo_documento "
                            + "inner join clientes as c on c.codigo = v.cliente "
                            + "where c.documento like '%" + busqueda + "%' or nombre_cliente like '%" + busqueda + "%'";

                }
                if (cbx_busqueda.getSelectedIndex() == 2) {
                    query = "select v.periodo, v.id, v.nro_placa, v.fecha_venta, td.abreviado as documento, v.serie_doc, v.nro_doc, c.documento as doc_cliente, v.nombre_cliente, v.kilometraje, v.total, v.descuento, v.pagado, v.estado "
                            + "from ventas as v "
                            + "inner join tipo_documento as td on td.id = v.tipo_documento "
                            + "inner join clientes as c on c.codigo = v.cliente "
                            + "where nro_placa = '" + busqueda + "'";
                }
                if (cbx_busqueda.getSelectedIndex() == 3) {

                    query = "select v.periodo, v.id, v.nro_placa, v.fecha_venta, td.abreviado as documento, v.serie_doc, v.nro_doc, c.documento as doc_cliente, v.nombre_cliente, v.kilometraje, v.total, v.descuento, v.pagado, v.estado "
                            + "from ventas as v "
                            + "inner join tipo_documento as td on td.id = v.tipo_documento "
                            + "inner join clientes as c on c.codigo = v.cliente "
                            + "where nro_doc = '" + busqueda + "'";

                }

                double total = c_venta.ver_ventas(t_ventas, query);
                txt_tot.setText(c_varios.formato_totales(total));
                txt_total_deudas.setText(c_varios.formato_totales(deudas_ventas()));
                cbx_busqueda.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(null, "POR FAVOR INGRESE DATOS PARA BUSCAR");
                txt_bus.requestFocus();
            }
        }

    }//GEN-LAST:event_txt_busKeyPressed

    private void btn_anuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anuActionPerformed
        if (fila_seleccionada > -1) {
            btn_ver_cobro.setEnabled(false);
            btn_modificar.setEnabled(false);
            btn_ver_detalle.setEnabled(false);
            btn_anu.setEnabled(false);

            int dialogButton = JOptionPane.YES_NO_OPTION;
            JOptionPane.showConfirmDialog(null, "Desea eliminar el registro seleccionado??", "Atencion", dialogButton);
            if (dialogButton == JOptionPane.YES_OPTION) { //The ISSUE is here
                c_venta.setCod_venta(t_ventas.getValueAt(fila_seleccionada, 0).toString());
                c_venta.datos_venta();

                c_detalle.setPeriodo(c_venta.getPeriodo());
                c_detalle.setVenta(c_venta.getCodigo());

                //eliminar detalle de venta
                c_detalle.eliminar();

                //eliminar cobro
                c_cobros.setPeriodo(c_venta.getPeriodo());
                c_cobros.setVenta(c_venta.getCodigo());

                c_cobros.eliminar_todo();

                //eliminar venta
                c_venta.eliminar();

                cargar_tabla();
            }
        } else {
            JOptionPane.showMessageDialog(null, "No ha seleccionado una fila");
        }
    }//GEN-LAST:event_btn_anuActionPerformed

    private void t_ventasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_ventasMousePressed
    }//GEN-LAST:event_t_ventasMousePressed

    private void btn_ver_cobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ver_cobroActionPerformed
        if (fila_seleccionada > -1) {
            btn_ver_cobro.setEnabled(false);
            btn_modificar.setEnabled(false);
            btn_ver_detalle.setEnabled(false);
            jd_ver_pagos.setModal(true);
            jd_ver_pagos.setSize(710, 380);
            jd_ver_pagos.setLocationRelativeTo(null);
            double total = Double.parseDouble(t_ventas.getValueAt(fila_seleccionada, 5).toString());
            txt_jd_cliente.setText(t_ventas.getValueAt(fila_seleccionada, 4).toString());
            txt_jd_iventa.setText(t_ventas.getValueAt(fila_seleccionada, 0).toString());
            txt_jd_placa.setText(t_ventas.getValueAt(fila_seleccionada, 3).toString());
            txt_jd_numero.setText(t_ventas.getValueAt(fila_seleccionada, 2).toString());
            txt_jd_total.setText(t_ventas.getValueAt(fila_seleccionada, 5).toString());
            c_cobros.setCod_venta(t_ventas.getValueAt(fila_seleccionada, 0).toString());
            c_venta.setCod_venta(c_cobros.getCod_venta());
            double pagado = c_cobros.mostrar_cobros(t_jd_pagos);
            txt_jd_porcobrar.setText(c_varios.formato_totales(total - pagado));
            if (total == pagado) {
                btn_jd_registrar.setEnabled(false);
            } else {
                btn_jd_registrar.setEnabled(true);
            }
            jd_ver_pagos.setVisible(true);
            btn_ver_cobro.setEnabled(false);
            btn_ver_detalle.setEnabled(false);
            btn_jd_registrar.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "No ha seleccionado una fila");
        }
    }//GEN-LAST:event_btn_ver_cobroActionPerformed

    private void t_ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_ventasMouseClicked
        fila_seleccionada = t_ventas.getSelectedRow();
        String estado = t_ventas.getValueAt(fila_seleccionada, 7).toString();
        if (estado.equals("ANULADO")) {
            btn_ver_cobro.setEnabled(false);
            btn_modificar.setEnabled(false);
            btn_ver_detalle.setEnabled(false);
            btn_anu.setEnabled(false);
        } else {
            btn_ver_cobro.setEnabled(true);
            btn_modificar.setEnabled(true);
            btn_ver_detalle.setEnabled(true);
            btn_anu.setEnabled(true);
        }
    }//GEN-LAST:event_t_ventasMouseClicked

    private void cbx_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_estadoActionPerformed
        if (cbx_estado.getSelectedIndex() == 1) {
            String query = "select v.periodo, v.id, v.nro_placa, v.fecha_venta, td.abreviado as documento, v.serie_doc, v.nro_doc, c.documento as doc_cliente, v.nombre_cliente, v.kilometraje, v.total, v.descuento, v.pagado, v.estado "
                    + "from ventas as v "
                    + "inner join tipo_documento as td on td.id = v.tipo_documento "
                    + "inner join clientes as c on c.codigo = v.cliente "
                    + "where v.estado = 0 "
                    + "order by v.id asc";
            double total = c_venta.ver_ventas(t_ventas, query);
            txt_tot.setText(c_varios.formato_totales(total));
            cbx_busqueda.setSelectedIndex(0);
            txt_total_deudas.setText(c_varios.formato_totales(deudas_ventas()));
            txt_bus.requestFocus();
        }
    }//GEN-LAST:event_cbx_estadoActionPerformed

    private void btn_ver_detalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ver_detalleActionPerformed
        if (fila_seleccionada > -1) {
            btn_ver_cobro.setEnabled(false);
            btn_modificar.setEnabled(false);
            btn_ver_detalle.setEnabled(false);
            jd_ver_detalle_venta.setModal(true);
            jd_ver_detalle_venta.setSize(710, 380);
            jd_ver_detalle_venta.setLocationRelativeTo(null);
            txt_jd_cliente1.setText(t_ventas.getValueAt(fila_seleccionada, 4).toString());
            txt_jd_iventa1.setText(t_ventas.getValueAt(fila_seleccionada, 0).toString());
            txt_jd_placa1.setText(t_ventas.getValueAt(fila_seleccionada, 3).toString());
            txt_jd_numero1.setText(t_ventas.getValueAt(fila_seleccionada, 2).toString());
            txt_jd_total1.setText(t_ventas.getValueAt(fila_seleccionada, 5).toString());
            c_venta.setCod_venta(t_ventas.getValueAt(fila_seleccionada, 0).toString());
            c_venta.datos_venta();
            c_detalle.setPeriodo(c_venta.getPeriodo());
            c_detalle.setVenta(c_venta.getCodigo());
            c_detalle.mostrar_productos(t_detalle);
            jd_ver_detalle_venta.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "No ha seleccionado una fila");
        }
    }//GEN-LAST:event_btn_ver_detalleActionPerformed

    private void t_jd_pagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_jd_pagosMouseClicked
        fila_pago = t_jd_pagos.getSelectedRow();
        btn_jd_eliminar_pago.setEnabled(true);
    }//GEN-LAST:event_t_jd_pagosMouseClicked

    private void t_jd_pagosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_jd_pagosKeyPressed

    }//GEN-LAST:event_t_jd_pagosKeyPressed


    private void btn_jd_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jd_cerrarActionPerformed
        jd_ver_pagos.dispose();
    }//GEN-LAST:event_btn_jd_cerrarActionPerformed

    private void btn_jd_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jd_registrarActionPerformed
        jd_reg_pago.setModal(true);
        jd_reg_pago.setSize(270, 188);
        jd_reg_pago.setLocationRelativeTo(null);
        txt_jda_fecha.setText(c_varios.formato_fecha_vista(c_varios.getFechaActual()));
        jd_reg_pago.setVisible(true);
    }//GEN-LAST:event_btn_jd_registrarActionPerformed

    private void btn_detalle_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detalle_cerrarActionPerformed
        jd_ver_detalle_venta.dispose();
    }//GEN-LAST:event_btn_detalle_cerrarActionPerformed

    private void txt_jda_fechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jda_fechaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_jda_fecha.getText().length() == 10) {
                cbx_jda_tipopago.setEnabled(true);
                cbx_jda_tipopago.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_jda_fechaKeyPressed

    private void cbx_jda_tipopagoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_jda_tipopagoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_jda_monto.setEnabled(true);
            txt_jda_monto.requestFocus();
        }
    }//GEN-LAST:event_cbx_jda_tipopagoKeyPressed


    private void txt_jda_montoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jda_montoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String monto = txt_jda_monto.getText();
            if (c_varios.esDecimal(monto)) {
                btn_jda_registrar.setEnabled(true);
                btn_jda_registrar.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_jda_montoKeyPressed

    private void txt_jda_montoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jda_montoKeyTyped

    }//GEN-LAST:event_txt_jda_montoKeyTyped

    private void btn_jda_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jda_registrarActionPerformed
        c_venta.datos_venta();
        c_cobros.setPeriodo(c_venta.getPeriodo());
        c_cobros.setVenta(c_venta.getCodigo());
        c_cobros.setCodigo(c_cobros.obtener_codigo());
        c_cobros.setFecha(c_varios.formato_fecha_mysql(txt_jda_fecha.getText()));
        c_cobros.setMonto(Double.parseDouble(txt_jda_monto.getText()));
        c_cobros.setTipo(cbx_jda_tipopago.getSelectedIndex() + 1);
        if (c_cobros.insertar()) {
            jd_reg_pago.dispose();
            double total = Double.parseDouble(t_ventas.getValueAt(fila_seleccionada, 5).toString());
            double pagado = c_cobros.mostrar_cobros(t_jd_pagos);
            txt_jd_porcobrar.setText(c_varios.formato_totales(total - pagado));
            if (total == pagado) {
                btn_jd_registrar.setEnabled(false);
            } else {
                btn_jd_registrar.requestFocus();
            }
        }
    }//GEN-LAST:event_btn_jda_registrarActionPerformed

    private void t_ventasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_ventasKeyPressed

    }//GEN-LAST:event_t_ventasKeyPressed

    private void btn_jd_eliminar_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jd_eliminar_pagoActionPerformed
        if (fila_pago > -1) {
            c_venta.datos_venta();
            c_cobros.setPeriodo(c_venta.getPeriodo());
            c_cobros.setVenta(c_venta.getCodigo());
            c_cobros.setCodigo(Integer.parseInt(t_jd_pagos.getValueAt(fila_pago, 0).toString()));
            if (c_cobros.eliminar()) {
                double total = Double.parseDouble(t_ventas.getValueAt(fila_seleccionada, 5).toString());
                double pagado = c_cobros.mostrar_cobros(t_jd_pagos);
                txt_jd_porcobrar.setText(c_varios.formato_totales(total - pagado));
                btn_jd_registrar.setEnabled(true);
                btn_jd_registrar.requestFocus();
            }
            btn_jd_eliminar_pago.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "No ha seleccionado una fila");
        }
    }//GEN-LAST:event_btn_jd_eliminar_pagoActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        if (fila_seleccionada > -1) {
            btn_ver_cobro.setEnabled(false);
            btn_modificar.setEnabled(false);
            btn_ver_detalle.setEnabled(false);
            jd_modificar_venta.setModal(true);
            jd_modificar_venta.setSize(710, 150);
            jd_modificar_venta.setLocationRelativeTo(null);
            c_venta.setCod_venta(t_ventas.getValueAt(fila_seleccionada, 0).toString());
            c_venta.datos_venta();
            txt_modificar_cliente.setText(t_ventas.getValueAt(fila_seleccionada, 4).toString());
            txt_modificar_placa.setText(t_ventas.getValueAt(fila_seleccionada, 3).toString());
            txt_modificar_documento.setText(t_ventas.getValueAt(fila_seleccionada, 2).toString());
            txt_modificar_fecha.setText(t_ventas.getValueAt(fila_seleccionada, 1).toString());
            txt_modificar_kilometraje.setText(c_venta.getKilometraje() + "");
            jd_modificar_venta.setVisible(true);
            txt_modificar_kilometraje.requestFocus();
        }
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_modificar_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificar_guardarActionPerformed
        c_venta.setKilometraje(Integer.parseInt(txt_modificar_kilometraje.getText()));
        if (c_venta.actualizar_kilometraje()) {
            jd_modificar_venta.dispose();
        }
    }//GEN-LAST:event_btn_modificar_guardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_anu;
    private javax.swing.JButton btn_detalle_cerrar;
    private javax.swing.JButton btn_jd_cerrar;
    private javax.swing.JButton btn_jd_eliminar_pago;
    private javax.swing.JButton btn_jd_registrar;
    private javax.swing.JButton btn_jda_registrar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_modificar_guardar;
    private javax.swing.JButton btn_ver_cobro;
    private javax.swing.JButton btn_ver_detalle;
    private javax.swing.JComboBox cbx_busqueda;
    private javax.swing.JComboBox cbx_estado;
    private javax.swing.JComboBox cbx_jda_tipopago;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JDialog jd_modificar_venta;
    private javax.swing.JDialog jd_reg_pago;
    private javax.swing.JDialog jd_ver_detalle_venta;
    private javax.swing.JDialog jd_ver_pagos;
    private javax.swing.JTable t_detalle;
    private javax.swing.JTable t_jd_pagos;
    private javax.swing.JTable t_ventas;
    private javax.swing.JTextField txt_bus;
    private javax.swing.JTextField txt_detalle_total;
    private javax.swing.JTextField txt_jd_cliente;
    private javax.swing.JTextField txt_jd_cliente1;
    private javax.swing.JTextField txt_jd_iventa;
    private javax.swing.JTextField txt_jd_iventa1;
    private javax.swing.JTextField txt_jd_moneda;
    private javax.swing.JTextField txt_jd_moneda1;
    private javax.swing.JTextField txt_jd_numero;
    private javax.swing.JTextField txt_jd_numero1;
    private javax.swing.JTextField txt_jd_placa;
    private javax.swing.JTextField txt_jd_placa1;
    private javax.swing.JTextField txt_jd_porcobrar;
    private javax.swing.JTextField txt_jd_total;
    private javax.swing.JTextField txt_jd_total1;
    private javax.swing.JFormattedTextField txt_jda_fecha;
    private javax.swing.JTextField txt_jda_monto;
    private javax.swing.JTextField txt_modificar_cliente;
    private javax.swing.JTextField txt_modificar_documento;
    private javax.swing.JFormattedTextField txt_modificar_fecha;
    private javax.swing.JTextField txt_modificar_kilometraje;
    private javax.swing.JTextField txt_modificar_placa;
    private javax.swing.JTextField txt_tot;
    private javax.swing.JTextField txt_total_deudas;
    // End of variables declaration//GEN-END:variables
}
