/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.cl_caja_chica;
import clases.cl_varios;
import java.awt.Frame;
import javax.swing.JOptionPane;
import models.m_caja_chica;

/**
 *
 * @author CALIDAD
 */
public class frm_ver_caja_mensual extends javax.swing.JInternalFrame {

    cl_caja_chica c_caja = new cl_caja_chica();
    cl_varios c_varios = new cl_varios();

    //modelos
    m_caja_chica m_caja = new m_caja_chica();

    /**
     * Creates new form frm_ver_caja_mensual
     */
    public frm_ver_caja_mensual() {
        initComponents();

        m_caja.cbx_anio(cbx_anio);
        String anio = cbx_anio.getSelectedItem().toString();
        m_caja.cbx_mes(cbx_mes, anio);
        String mes = cbx_mes.getSelectedItem().toString();
        String query = "select * "
                + "from caja_chica "
                + "where year(fecha) = '" + anio + "' and month(fecha) = '" + mes + "' "
                + "order by fecha desc";
        c_caja.ver_caja_mensual(t_mensual, query);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        t_mensual = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cbx_anio = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbx_mes = new javax.swing.JComboBox();
        btn_mostrar = new javax.swing.JButton();
        btn_cerrar = new javax.swing.JButton();

        setTitle("Ver Caja Mensual");

        t_mensual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_mensual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_mensualMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t_mensual);

        jLabel1.setText("Seleccionar Año:");

        cbx_anio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_anioItemStateChanged(evt);
            }
        });

        jLabel2.setText("Seleccionar Mes:");

        cbx_mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar Año" }));
        cbx_mes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_mesItemStateChanged(evt);
            }
        });

        btn_mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/find.png"))); // NOI18N
        btn_mostrar.setText("Mostrar");
        btn_mostrar.setEnabled(false);
        btn_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarActionPerformed(evt);
            }
        });

        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cancel.png"))); // NOI18N
        btn_cerrar.setText("Cerrar");
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_mostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                        .addComponent(btn_cerrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void t_mensualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_mensualMouseClicked
        if (evt.getClickCount() == 2) {
            int fila_seleccionada = t_mensual.getSelectedRow();
            String fecha_seleccionada = c_varios.formato_fecha_mysql(t_mensual.getValueAt(fila_seleccionada, 0).toString());
            Frame f = JOptionPane.getRootFrame();
            frm_ver_caja_diaria.fecha = fecha_seleccionada;
            frm_ver_caja_diaria.origen = "ver_datos";
            frm_ver_caja_diaria dialog = new frm_ver_caja_diaria(f, true);
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_t_mensualMouseClicked

    private void cbx_anioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_anioItemStateChanged
        String anio = cbx_anio.getSelectedItem().toString();
        cbx_mes.removeAllItems();
        m_caja.cbx_mes(cbx_mes, anio);
        cbx_mes.requestFocus();
    }//GEN-LAST:event_cbx_anioItemStateChanged

    private void cbx_mesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_mesItemStateChanged
        btn_mostrar.setEnabled(true);
        btn_mostrar.requestFocus();
    }//GEN-LAST:event_cbx_mesItemStateChanged

    private void btn_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarActionPerformed
        String anio = cbx_anio.getSelectedItem().toString();
        String mes = cbx_mes.getSelectedItem().toString();
        String query = "select * "
                + "from caja_chica "
                + "where year(fecha) = '" + anio + "' and month(fecha) = '" + mes + "' "
                + "order by fecha desc";
        c_caja.ver_caja_mensual(t_mensual, query);
    }//GEN-LAST:event_btn_mostrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_mostrar;
    private javax.swing.JComboBox cbx_anio;
    private javax.swing.JComboBox cbx_mes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t_mensual;
    // End of variables declaration//GEN-END:variables
}
